import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 侧边栏由 docs/ 目录结构自动生成：
// - 新增/重命名/删除文档或目录后重新构建即可，无需修改本文件
// - 显示顺序通过各文档 frontmatter 的 sidebar_position 控制（数字越小越靠前）
// - 分类标签与顺序通过各目录下的 _category_.yml 控制
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
